spring:

  application:
    name: drinking_game

  datasource:
    username: root
    password: PYm%HI6SLffT
    url: jdbc:mysql://localhost:3306/drinking_game_database?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

drinking_game:
  security:
    token:
      secret: secret
